# Default values for emitter_helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/campaignmgr/campaign_emitter_doc
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

envs:
   - name: DISTRIBUTED_NODES
     value: "\'campaign_scheduler@campaign-scheduler-0.headless-svc.default.svc.cluster.local\'"
   - name: SENDER_UPADTE_FREQUENCY
     value: !!integer 5              
   - name: SENDER_RECORD_LIMIT
     value: !!integer 50 
   - name: SENDER_UPDATE_RECORD_COUNT
     value: !!integer 10 
   - name: SENDER_VERBOSITY
     value: !!integer 7 
   - name: CAMPAIGN_ESME_LIST
     value: "[esme_gsm]" 
   - name: COMPOSE_API_ROOT
     value: "10.0.0.99:4000" 
   - name: IVR_BLOCK
     value: "1" 
   - name: RECEIVER_VERBOSITY
     value: !!integer 7 
   - name: RECEIVER_SERVER_COUNT
     value: !!integer 10 
   - name: DELIVERY_REPORPROCESSING_DELAY
     value: !!integer 100 
   - name: FILTER_LIST
     value: "[cm_filter_service_blacklist, cm_filter_blacklist]" 
   - name: FILTER_SERVER_COUNT
     value: !!integer 10 
   - name: FILTER_VERBOSITY
     value: !!integer 7 
   - name: MMS_INSTANCES
     value: !!integer 10 
   - name: APP_PORT
     value: !!integer 8087 
   - name: MM7_VERBOSITY
     value: !!integer 7 
   - name: MM7_VERSION
     value: "6.4.0" 
   - name: MM7_SCHEMA_VERSION
     value: "true" 
   - name: VASP_ID
     value: "NEWS" 
   - name: VAS_ID
     value: "TNN" 
   - name: MM7_SERVICE_CODE
     value: "gold-sp33-im42" 
   - name: MM7_DELIVERY_REPORT
     value: "true" 
   - name: MM7_LINKED_ID
     value: "mms00016666" 
   - name: MM7_MSG_CLASS
     value: "Informational" 
   - name: MM7_REPLY_CHARGING
     value: undefined 
   - name: MM7_READ_REPLY
     value: "false" 
   - name: MM7_PRIORITY
     value: "Normal" 
   - name: MM7_SUBJECT
     value: "Subject" 
   - name: MM7_CHARGED_PARTY
     value: "Sender" 
   - name: MM7_CHARGED_PARTY_ID
     value: "undefined" 
   - name: MM7_DISTRIBUTION_INDICATOR
     value: "false" 
   - name: MM7_DELIVERY_CONDITION
     value: "undefined" 
   - name: MM7_APP_ID
     value: "undefined" 
   - name: MM7_REPLY_APP_ID
     value: "undefined" 
   - name: MM7_AUX_INFO
     value: "undefined" 
   - name: MM7_CONTENT_CLASS
     value: "Video-rich" 
   - name: MM7_DRM_CONTENT
     value: "false" 
   - name: MM7_EARLIEST_DELIVERY
     value: !!integer 1000 
   - name: MM7_EXPIRY
     value: !!integer 10000 
   - name: MM7_CONTENT_PATH
     value: "/usr/local/var/yaws/www/campaign_manager/tmp/mms_content/" 
   - name: MM7_SOAP_URL
     value: "http://10.0.0.69:8090" 
   - name: MM7_ATTACHMENT
     value: "true" 
   - name: DNS
     value: "DSN=campaign_mgr;UID=root;PWD=Omnibis.123" 
   - name: ODBC_NORMAL_POOL_SIZE
     value: !!integer 5 
   - name: ODBC_TRANSACTION_POOL_SIZE
     value: !!integer 0 
   - name: ODBC_NORMAL_SECOND_POOL_SIZE
     value: !!integer 0 
   - name: ODBC_TRANSACTION_SECOND_POOL_SIZE
     value: !!integer 0 
   - name: ODBC_VERBOSITY
     value: !!integer 7 
   - name: ODBC_CONN_TIMEOUT
     value: !!integer 10000 
   - name: VOTING_ESME_LIST
     value: "[esme_gsm1]" 
   - name: LOG_NODE
     value: "prime_log_21@true_smsbc_01" 
   - name: DB_SERVER_IP
     value: "34.75.81.191" 
   - name: DB_SERVER_UID
     value: "root" 
   - name: DB_SERVER_PW
     value: "Omnibis.123" 
   - name: DATABASE
     value: "campaign_mgr" 
   - name: SMPP_HOST_IP1
     value: "10.0.0.69" 
   - name: SMPP_HOST_PORT1
     value: !!integer 2781 
   - name: SMPP_SYSTEM_ID1
     value: "trueqaacc01" 
   - name: SMPP_PASSWORD1
     value: "test1" 
   - name: SMPP_TROTTLE1
     value: !!integer 50 
   - name: SMPP_HOST_IP2
     value: "10.0.0.69" 
   - name: SMPP_HOST_PORT2
     value: !!integer 2781 
   - name: SMPP_SYSTEM_ID2
     value: "trueqaacc02" 
   - name: SMPP_PASSWORD2
     value: "test2" 
   - name: SMPP_TROTTLE2
     value: !!integer 50 

terminationGracePeriod: 30

readiness:
    InitialDelaySeconds: 300
    PeriodSeconds: 30
    SuccessThreshold: 1
    FailureThreshold: 100
    TimeoutSeconds: 30

liveness:
    InitialDelaySeconds: 30
    PeriodSeconds: 30
    SuccessThreshold: 1
    FailureThreshold: 100
    TimeoutSeconds: 30

volumnMountPath: /usr/local/var/yaws/www/campaign_manager/tmp/

imagePullSecrets: 
    - name: nexusjenkins
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
