apiVersion: v1
kind: Service
metadata:
  name: campaign-manager-admin-1
  labels:
    app: campaign-manager-admin
spec:
  type: ClusterIP
  selector:
    app: campaign-manager-admin
  ports:
  - name: admin
    protocol: TCP
    port: 8002
    targetPort: 8002
