apiVersion: v1
kind: Service
metadata:
  name: campaign-manager-admin
  labels:
    app: campaign-manager-admin
spec:
  type: {{ .Values.service.type }}
  selector:
    app: campaign-manager-admin
  ports:
  - name: admin
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
