apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  # clusterIP: 10.3.240.20
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .containerPort }}
    {{- end }}  
  selector:
    role: nfs-server